{{- if .Values.blockchain.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clearnet.fullname" . }}-blockchain
  labels:
    {{- include "clearnet.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: blockchain
  ports:
    - name: rpc
      port: {{ .Values.blockchain.port }}
      targetPort: rpc
      protocol: TCP
{{- end }}