{{- if not .Values.neo4j.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clearnet.fullname" . }}-neo4j-secret
  labels:
    {{- include "clearnet.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.neo4j.authPassword | b64enc | quote }}
{{- end }}